<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Track;

class TrackSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
Track::create(["name" => "Cochise", "duration" => "222380", "album_id" => "1"]);
Track::create(["name" => "Show Me How to Live", "duration" => "277890", "album_id" => "1"]);
Track::create(["name" => "Gasoline", "duration" => "279457", "album_id" => "1"]);
Track::create(["name" => "What You Are", "duration" => "249391", "album_id" => "1"]);
Track::create(["name" => "Like a Stone", "duration" => "294034", "album_id" => "1"]);
Track::create(["name" => "Set It Off", "duration" => "263262", "album_id" => "1"]);
Track::create(["name" => "Shadow on the Sun", "duration" => "343457", "album_id" => "1"]);
Track::create(["name" => "I am the Highway", "duration" => "334942", "album_id" => "1"]);
Track::create(["name" => "Exploder", "duration" => "206053", "album_id" => "1"]);
Track::create(["name" => "Hypnotize", "duration" => "206628", "album_id" => "1"]);
Track::create(["name" => "Bring'em Back Alive", "duration" => "329534", "album_id" => "1"]);
Track::create(["name" => "Light My Way", "duration" => "303595", "album_id" => "1"]);
Track::create(["name" => "Getaway Car", "duration" => "299598", "album_id" => "1"]);
Track::create(["name" => "The Last Remaining Light", "duration" => "317492", "album_id" => "1"]);
Track::create(["name" => "Your Time Has Come", "duration" => "255529", "album_id" => "2"]);
Track::create(["name" => "Out Of Exile", "duration" => "291291", "album_id" => "2"]);
Track::create(["name" => "Be Yourself", "duration" => "279484", "album_id" => "2"]);
Track::create(["name" => "Doesn't Remind Me", "duration" => "255869", "album_id" => "2"]);
Track::create(["name" => "Drown Me Slowly", "duration" => "233691", "album_id" => "2"]);
Track::create(["name" => "Heaven's Dead", "duration" => "276688", "album_id" => "2"]);
Track::create(["name" => "The Worm", "duration" => "237714", "album_id" => "2"]);
Track::create(["name" => "Man Or Animal", "duration" => "233195", "album_id" => "2"]);
Track::create(["name" => "Yesterday To Tomorrow", "duration" => "273763", "album_id" => "2"]);
Track::create(["name" => "Dandelion", "duration" => "278125", "album_id" => "2"]);
Track::create(["name" => "#1 Zero", "duration" => "299102", "album_id" => "2"]);
Track::create(["name" => "The Curse", "duration" => "309786", "album_id" => "2"]);
Track::create(["name" => "You Shook Me", "duration" => "315951", "album_id" => "4"]);
Track::create(["name" => "I Can't Quit You Baby", "duration" => "263836", "album_id" => "4"]);
Track::create(["name" => "Communication Breakdown", "duration" => "192653", "album_id" => "4"]);
Track::create(["name" => "Dazed and Confused", "duration" => "401920", "album_id" => "4"]);
Track::create(["name" => "The Girl I Love She Got Long Black Wavy Hair", "duration" => "183327", "album_id" => "4"]);
Track::create(["name" => "What is and Should Never Be", "duration" => "260675", "album_id" => "4"]);
Track::create(["name" => "Communication Breakdown(2)", "duration" => "161149", "album_id" => "4"]);
Track::create(["name" => "Travelling Riverside Blues", "duration" => "312032", "album_id" => "4"]);
Track::create(["name" => "Whole Lotta Love", "duration" => "373394", "album_id" => "4"]);
Track::create(["name" => "Somethin' Else", "duration" => "127869", "album_id" => "4"]);
Track::create(["name" => "Communication Breakdown(3)", "duration" => "185260", "album_id" => "4"]);
Track::create(["name" => "I Can't Quit You Baby(2)", "duration" => "380551", "album_id" => "4"]);
Track::create(["name" => "You Shook Me(2)", "duration" => "619467", "album_id" => "4"]);
Track::create(["name" => "How Many More Times", "duration" => "711836", "album_id" => "4"]);
Track::create(["name" => "Free Speech For The Dumb", "duration" => "155428", "album_id" => "18"]);
Track::create(["name" => "It's Electric", "duration" => "213995", "album_id" => "18"]);
Track::create(["name" => "Sabbra Cadabra", "duration" => "380342", "album_id" => "18"]);
Track::create(["name" => "Turn The Page", "duration" => "366524", "album_id" => "18"]);
Track::create(["name" => "Die Die My Darling", "duration" => "149315", "album_id" => "18"]);
Track::create(["name" => "Loverman", "duration" => "472764", "album_id" => "18"]);
Track::create(["name" => "Mercyful Fate", "duration" => "671712", "album_id" => "18"]);
Track::create(["name" => "Astronomy", "duration" => "397531", "album_id" => "18"]);
Track::create(["name" => "Whiskey In The Jar", "duration" => "305005", "album_id" => "18"]);
Track::create(["name" => "Tuesday's Gone", "duration" => "545750", "album_id" => "18"]);
Track::create(["name" => "The More I See", "duration" => "287973", "album_id" => "18"]);
Track::create(["name" => "A Kind Of Magic", "duration" => "262608", "album_id" => "28"]);
Track::create(["name" => "Under Pressure", "duration" => "236617", "album_id" => "28"]);
Track::create(["name" => "Radio GA GA", "duration" => "343745", "album_id" => "28"]);
Track::create(["name" => "I Want It All", "duration" => "241684", "album_id" => "28"]);
Track::create(["name" => "I Want To Break Free", "duration" => "259108", "album_id" => "28"]);
Track::create(["name" => "Innuendo", "duration" => "387761", "album_id" => "28"]);
Track::create(["name" => "It's A Hard Life", "duration" => "249417", "album_id" => "28"]);
Track::create(["name" => "Breakthru", "duration" => "249234", "album_id" => "28"]);
Track::create(["name" => "Who Wants To Live Forever", "duration" => "297691", "album_id" => "28"]);
Track::create(["name" => "Headlong", "duration" => "273057", "album_id" => "28"]);
Track::create(["name" => "The Miracle", "duration" => "294974", "album_id" => "28"]);
Track::create(["name" => "I'm Going Slightly Mad", "duration" => "248032", "album_id" => "28"]);
Track::create(["name" => "The Invisible Man", "duration" => "238994", "album_id" => "28"]);
Track::create(["name" => "Hammer To Fall", "duration" => "220316", "album_id" => "28"]);
Track::create(["name" => "Friends Will Be Friends", "duration" => "248920", "album_id" => "28"]);
Track::create(["name" => "The Show Must Go On", "duration" => "263784", "album_id" => "28"]);
Track::create(["name" => "One Vision", "duration" => "242599", "album_id" => "28"]);
Track::create(["name" => "Custard Pie", "duration" => "253962", "album_id" => "5"]);
Track::create(["name" => "The Rover", "duration" => "337084", "album_id" => "5"]);
Track::create(["name" => "In My Time Of Dying", "duration" => "666017", "album_id" => "5"]);
Track::create(["name" => "Houses Of The Holy", "duration" => "242494", "album_id" => "5"]);
Track::create(["name" => "Trampled Under Foot", "duration" => "336692", "album_id" => "5"]);
Track::create(["name" => "Kashmir", "duration" => "508604", "album_id" => "5"]);
Track::create(["name" => "Pour Some Sugar On Me", "duration" => "292519", "album_id" => "31"]);
Track::create(["name" => "Photograph", "duration" => "248633", "album_id" => "31"]);
Track::create(["name" => "Love Bites", "duration" => "346853", "album_id" => "31"]);
Track::create(["name" => "Let's Get Rocked", "duration" => "296019", "album_id" => "31"]);
Track::create(["name" => "Two Steps Behind [Acoustic Version]", "duration" => "259787", "album_id" => "31"]);
Track::create(["name" => "Animal", "duration" => "244741", "album_id" => "31"]);
Track::create(["name" => "Heaven Is", "duration" => "214021", "album_id" => "31"]);
Track::create(["name" => "Rocket", "duration" => "247248", "album_id" => "31"]);
Track::create(["name" => "When Love & Hate Collide", "duration" => "257280", "album_id" => "31"]);
Track::create(["name" => "Action", "duration" => "220604", "album_id" => "31"]);
Track::create(["name" => "Make Love Like A Man", "duration" => "255660", "album_id" => "31"]);
Track::create(["name" => "Armageddon It", "duration" => "322455", "album_id" => "31"]);
Track::create(["name" => "Have You Ever Needed Someone So Bad", "duration" => "319320", "album_id" => "31"]);
Track::create(["name" => "Rock Of Ages", "duration" => "248424", "album_id" => "31"]);
Track::create(["name" => "Hysteria", "duration" => "355056", "album_id" => "31"]);
Track::create(["name" => "Bringin' On The Heartbreak", "duration" => "272457", "album_id" => "31"]);
Track::create(["name" => "Collision", "duration" => "204303", "album_id" => "32"]);
Track::create(["name" => "Stripsearch", "duration" => "270106", "album_id" => "32"]);
Track::create(["name" => "Last Cup Of Sorrow", "duration" => "251663", "album_id" => "32"]);
Track::create(["name" => "Naked In Front Of The Computer", "duration" => "128757", "album_id" => "32"]);
Track::create(["name" => "Helpless", "duration" => "326217", "album_id" => "32"]);
Track::create(["name" => "Mouth To Mouth", "duration" => "228493", "album_id" => "32"]);
Track::create(["name" => "Ashes To Ashes", "duration" => "217391", "album_id" => "32"]);
Track::create(["name" => "She Loves Me Not", "duration" => "209867", "album_id" => "32"]);
Track::create(["name" => "Got That Feeling", "duration" => "140852", "album_id" => "32"]);
Track::create(["name" => "Paths Of Glory", "duration" => "257253", "album_id" => "32"]);
Track::create(["name" => "Home Sick Home", "duration" => "119040", "album_id" => "32"]);
Track::create(["name" => "Pristina", "duration" => "232698", "album_id" => "32"]);
Track::create(["name" => "Land Of Sunshine", "duration" => "223921", "album_id" => "33"]);
Track::create(["name" => "Caffeine", "duration" => "267937", "album_id" => "33"]);
Track::create(["name" => "Midlife Crisis", "duration" => "263235", "album_id" => "33"]);
Track::create(["name" => "RV", "duration" => "223242", "album_id" => "33"]);
Track::create(["name" => "Smaller And Smaller", "duration" => "310831", "album_id" => "33"]);
Track::create(["name" => "Everything's Ruined", "duration" => "273658", "album_id" => "33"]);
Track::create(["name" => "Malpractice", "duration" => "241371", "album_id" => "33"]);
Track::create(["name" => "Kindergarten", "duration" => "270680", "album_id" => "33"]);
Track::create(["name" => "Be Aggressive", "duration" => "222432", "album_id" => "33"]);
Track::create(["name" => "A Small Victory", "duration" => "297168", "album_id" => "33"]);
Track::create(["name" => "Crack Hitler", "duration" => "279144", "album_id" => "33"]);
Track::create(["name" => "Jizzlobber", "duration" => "398341", "album_id" => "33"]);
Track::create(["name" => "Midnight Cowboy", "duration" => "251924", "album_id" => "33"]);
Track::create(["name" => "Easy", "duration" => "185835", "album_id" => "33"]);
Track::create(["name" => "Get Out", "duration" => "137482", "album_id" => "34"]);
Track::create(["name" => "Ricochet", "duration" => "269400", "album_id" => "34"]);
Track::create(["name" => "Evidence", "duration" => "293590", "album_id" => "34"]);
Track::create(["name" => "The Gentle Art Of Making Enemies", "duration" => "209319", "album_id" => "34"]);
Track::create(["name" => "Star A.D.", "duration" => "203807", "album_id" => "34"]);
Track::create(["name" => "Cuckoo For Caca", "duration" => "222902", "album_id" => "34"]);
Track::create(["name" => "Caralho Voador", "duration" => "242102", "album_id" => "34"]);
Track::create(["name" => "Ugly In The Morning", "duration" => "186435", "album_id" => "34"]);
Track::create(["name" => "Digging The Grave", "duration" => "185129", "album_id" => "34"]);
Track::create(["name" => "Take This Bottle", "duration" => "298997", "album_id" => "34"]);
Track::create(["name" => "King For A Day", "duration" => "395859", "album_id" => "34"]);
Track::create(["name" => "What A Day", "duration" => "158275", "album_id" => "34"]);
Track::create(["name" => "The Last To Know", "duration" => "267833", "album_id" => "34"]);
Track::create(["name" => "Just A Man", "duration" => "336666", "album_id" => "34"]);
Track::create(["name" => "Absolute Zero", "duration" => "181995", "album_id" => "34"]);
Track::create(["name" => "From Out Of Nowhere", "duration" => "202527", "album_id" => "35"]);
Track::create(["name" => "Epic", "duration" => "294008", "album_id" => "35"]);
Track::create(["name" => "Falling To Pieces", "duration" => "316055", "album_id" => "35"]);
Track::create(["name" => "Surprise! You're Dead!", "duration" => "147226", "album_id" => "35"]);
Track::create(["name" => "Zombie Eaters", "duration" => "360881", "album_id" => "35"]);
Track::create(["name" => "The Real Thing", "duration" => "493635", "album_id" => "35"]);
Track::create(["name" => "Underwater Love", "duration" => "231993", "album_id" => "35"]);
Track::create(["name" => "The Morning After", "duration" => "223764", "album_id" => "35"]);
Track::create(["name" => "Woodpecker From Mars", "duration" => "340532", "album_id" => "35"]);
Track::create(["name" => "War Pigs", "duration" => "464770", "album_id" => "35"]);
Track::create(["name" => "Edge Of The World", "duration" => "250357", "album_id" => "35"]);
Track::create(["name" => "In Your Honor", "duration" => "230191", "album_id" => "36"]);
Track::create(["name" => "No Way Back", "duration" => "196675", "album_id" => "36"]);
Track::create(["name" => "Best Of You", "duration" => "255712", "album_id" => "36"]);
Track::create(["name" => "DOA", "duration" => "252186", "album_id" => "36"]);
Track::create(["name" => "Hell", "duration" => "117080", "album_id" => "36"]);
Track::create(["name" => "The Last Song", "duration" => "199523", "album_id" => "36"]);
Track::create(["name" => "Free Me", "duration" => "278700", "album_id" => "36"]);
Track::create(["name" => "Resolve", "duration" => "288731", "album_id" => "36"]);
Track::create(["name" => "The Deepest Blues Are Black", "duration" => "238419", "album_id" => "36"]);
Track::create(["name" => "End Over End", "duration" => "352078", "album_id" => "36"]);
Track::create(["name" => "Still", "duration" => "313182", "album_id" => "37"]);
Track::create(["name" => "What If I Do?", "duration" => "302994", "album_id" => "37"]);
Track::create(["name" => "Miracle", "duration" => "209684", "album_id" => "37"]);
Track::create(["name" => "Another Round", "duration" => "265848", "album_id" => "37"]);
Track::create(["name" => "Friend Of A Friend", "duration" => "193280", "album_id" => "37"]);
Track::create(["name" => "Over And Out", "duration" => "316264", "album_id" => "37"]);
Track::create(["name" => "On The Mend", "duration" => "271908", "album_id" => "37"]);
Track::create(["name" => "Virginia Moon", "duration" => "229198", "album_id" => "37"]);
Track::create(["name" => "Cold Day In The Sun", "duration" => "200724", "album_id" => "37"]);
Track::create(["name" => "Razor", "duration" => "293276", "album_id" => "37"]);
Track::create(["name" => "All My Life", "duration" => "263653", "album_id" => "38"]);
Track::create(["name" => "Low", "duration" => "268120", "album_id" => "38"]);
Track::create(["name" => "Have It All", "duration" => "298057", "album_id" => "38"]);
Track::create(["name" => "Times Like These", "duration" => "266370", "album_id" => "38"]);
Track::create(["name" => "Disenchanted Lullaby", "duration" => "273528", "album_id" => "38"]);
Track::create(["name" => "Tired Of You", "duration" => "311353", "album_id" => "38"]);
Track::create(["name" => "Halo", "duration" => "306442", "album_id" => "38"]);
Track::create(["name" => "Lonely As You", "duration" => "277185", "album_id" => "38"]);
Track::create(["name" => "Overdrive", "duration" => "270550", "album_id" => "38"]);
Track::create(["name" => "Burn Away", "duration" => "298396", "album_id" => "38"]);
Track::create(["name" => "Come Back", "duration" => "469968", "album_id" => "38"]);
Track::create(["name" => "Doll", "duration" => "83487", "album_id" => "39"]);
Track::create(["name" => "Monkey Wrench", "duration" => "231523", "album_id" => "39"]);
Track::create(["name" => "Hey, Johnny Park!", "duration" => "248528", "album_id" => "39"]);
Track::create(["name" => "My Poor Brain", "duration" => "213446", "album_id" => "39"]);
Track::create(["name" => "Wind Up", "duration" => "152163", "album_id" => "39"]);
Track::create(["name" => "Up In Arms", "duration" => "135732", "album_id" => "39"]);
Track::create(["name" => "My Hero", "duration" => "260101", "album_id" => "39"]);
Track::create(["name" => "See You", "duration" => "146782", "album_id" => "39"]);
Track::create(["name" => "Enough Space", "duration" => "157387", "album_id" => "39"]);
Track::create(["name" => "February Stars", "duration" => "289306", "album_id" => "39"]);
Track::create(["name" => "Everlong", "duration" => "250749", "album_id" => "39"]);
Track::create(["name" => "Walking After You", "duration" => "303856", "album_id" => "39"]);
Track::create(["name" => "New Way Home", "duration" => "342230", "album_id" => "39"]);
Track::create(["name" => "Welcome to the Jungle", "duration" => "273552", "album_id" => "40"]);
Track::create(["name" => "It's So Easy", "duration" => "202824", "album_id" => "40"]);
Track::create(["name" => "Nightrain", "duration" => "268537", "album_id" => "40"]);
Track::create(["name" => "Out Ta Get Me", "duration" => "263893", "album_id" => "40"]);
Track::create(["name" => "Mr. Brownstone", "duration" => "228924", "album_id" => "40"]);
Track::create(["name" => "Paradise City", "duration" => "406347", "album_id" => "40"]);
Track::create(["name" => "My Michelle", "duration" => "219961", "album_id" => "40"]);
Track::create(["name" => "Think About You", "duration" => "231640", "album_id" => "40"]);
Track::create(["name" => "Sweet Child O' Mine", "duration" => "356424", "album_id" => "40"]);
Track::create(["name" => "You're Crazy", "duration" => "197135", "album_id" => "40"]);
Track::create(["name" => "Anything Goes", "duration" => "206400", "album_id" => "40"]);
Track::create(["name" => "Rocket Queen", "duration" => "375349", "album_id" => "40"]);
Track::create(["name" => "Right Next Door to Hell", "duration" => "182321", "album_id" => "41"]);
Track::create(["name" => "Dust N' Bones", "duration" => "298374", "album_id" => "41"]);
Track::create(["name" => "Live and Let Die", "duration" => "184016", "album_id" => "41"]);
Track::create(["name" => "Don't Cry (Original)", "duration" => "284744", "album_id" => "41"]);
Track::create(["name" => "Perfect Crime", "duration" => "143637", "album_id" => "41"]);
Track::create(["name" => "You Ain't the First", "duration" => "156268", "album_id" => "41"]);
Track::create(["name" => "Bad Obsession", "duration" => "328282", "album_id" => "41"]);
Track::create(["name" => "Back off Bitch", "duration" => "303436", "album_id" => "41"]);
Track::create(["name" => "Double Talkin' Jive", "duration" => "203637", "album_id" => "41"]);
Track::create(["name" => "November Rain", "duration" => "537540", "album_id" => "41"]);
Track::create(["name" => "The Garden", "duration" => "322175", "album_id" => "41"]);
Track::create(["name" => "Garden of Eden", "duration" => "161539", "album_id" => "41"]);
Track::create(["name" => "Don't Damn Me", "duration" => "318901", "album_id" => "41"]);
Track::create(["name" => "Bad Apples", "duration" => "268351", "album_id" => "41"]);
Track::create(["name" => "Dead Horse", "duration" => "257600", "album_id" => "41"]);
Track::create(["name" => "Coma", "duration" => "616511", "album_id" => "41"]);
Track::create(["name" => "Civil War", "duration" => "461165", "album_id" => "42"]);
Track::create(["name" => "14 Years", "duration" => "261355", "album_id" => "42"]);
Track::create(["name" => "Yesterdays", "duration" => "196205", "album_id" => "42"]);
Track::create(["name" => "Knockin' On Heaven's Door", "duration" => "336457", "album_id" => "42"]);
Track::create(["name" => "Get In The Ring", "duration" => "341054", "album_id" => "42"]);
Track::create(["name" => "Shotgun Blues", "duration" => "203206", "album_id" => "42"]);
Track::create(["name" => "Breakdown", "duration" => "424960", "album_id" => "42"]);
Track::create(["name" => "Pretty Tied Up", "duration" => "287477", "album_id" => "42"]);
Track::create(["name" => "Locomotive", "duration" => "522396", "album_id" => "42"]);
Track::create(["name" => "So Fine", "duration" => "246491", "album_id" => "42"]);
Track::create(["name" => "Estranged", "duration" => "563800", "album_id" => "42"]);
Track::create(["name" => "You Could Be Mine", "duration" => "343875", "album_id" => "42"]);
Track::create(["name" => "Don't Cry", "duration" => "284238", "album_id" => "42"]);
Track::create(["name" => "My World", "duration" => "84532", "album_id" => "42"]);
Track::create(["name" => "Foxy Lady", "duration" => "199340", "album_id" => "43"]);
Track::create(["name" => "Manic Depression", "duration" => "222302", "album_id" => "43"]);
Track::create(["name" => "Red House", "duration" => "224130", "album_id" => "43"]);
Track::create(["name" => "Can You See Me", "duration" => "153077", "album_id" => "43"]);
Track::create(["name" => "Love Or Confusion", "duration" => "193123", "album_id" => "43"]);
Track::create(["name" => "I Don't Live Today", "duration" => "235311", "album_id" => "43"]);
Track::create(["name" => "May This Be Love", "duration" => "191216", "album_id" => "43"]);
Track::create(["name" => "Fire", "duration" => "164989", "album_id" => "43"]);
Track::create(["name" => "Third Stone From The Sun", "duration" => "404453", "album_id" => "43"]);
Track::create(["name" => "Remember", "duration" => "168150", "album_id" => "43"]);
Track::create(["name" => "Are You Experienced?", "duration" => "254537", "album_id" => "43"]);
Track::create(["name" => "Hey Joe", "duration" => "210259", "album_id" => "43"]);
Track::create(["name" => "Stone Free", "duration" => "216293", "album_id" => "43"]);
Track::create(["name" => "Purple Haze", "duration" => "171572", "album_id" => "43"]);
Track::create(["name" => "51st Anniversary", "duration" => "196388", "album_id" => "43"]);
Track::create(["name" => "The Wind Cries Mary", "duration" => "200463", "album_id" => "43"]);
Track::create(["name" => "Highway Chile", "duration" => "212453", "album_id" => "43"]);
Track::create(["name" => "Immigrant Song", "duration" => "201247", "album_id" => "6"]);
Track::create(["name" => "Heartbreaker", "duration" => "316081", "album_id" => "6"]);
Track::create(["name" => "Since I've Been Loving You", "duration" => "416365", "album_id" => "6"]);
Track::create(["name" => "Black Dog", "duration" => "317622", "album_id" => "6"]);
Track::create(["name" => "Dazed And Confused", "duration" => "1116734", "album_id" => "6"]);
Track::create(["name" => "Stairway To Heaven", "duration" => "529658", "album_id" => "6"]);
Track::create(["name" => "Going To California", "duration" => "234605", "album_id" => "6"]);
Track::create(["name" => "That's The Way", "duration" => "343431", "album_id" => "6"]);
Track::create(["name" => "Whole Lotta Love (Medley)", "duration" => "825103", "album_id" => "6"]);
Track::create(["name" => "Thank You", "duration" => "398262", "album_id" => "6"]);
Track::create(["name" => "We're Gonna Groove", "duration" => "157570", "album_id" => "7"]);
Track::create(["name" => "Poor Tom", "duration" => "182491", "album_id" => "7"]);
Track::create(["name" => "I Can't Quit You Baby", "duration" => "258168", "album_id" => "7"]);
Track::create(["name" => "Walter's Walk", "duration" => "270785", "album_id" => "7"]);
Track::create(["name" => "Ozone Baby", "duration" => "215954", "album_id" => "7"]);
Track::create(["name" => "Darlene", "duration" => "307226", "album_id" => "7"]);
Track::create(["name" => "Bonzo's Montreux", "duration" => "258925", "album_id" => "7"]);
Track::create(["name" => "Wearing And Tearing", "duration" => "330004", "album_id" => "7"]);
Track::create(["name" => "The Song Remains The Same", "duration" => "330004", "album_id" => "8"]);
Track::create(["name" => "The Rain Song", "duration" => "459180", "album_id" => "8"]);
Track::create(["name" => "Over The Hills And Far Away", "duration" => "290089", "album_id" => "8"]);
Track::create(["name" => "The Crunge", "duration" => "197407", "album_id" => "8"]);
Track::create(["name" => "Dancing Days", "duration" => "223216", "album_id" => "8"]);
Track::create(["name" => "D'Yer Mak'er", "duration" => "262948", "album_id" => "8"]);
Track::create(["name" => "No Quarter", "duration" => "420493", "album_id" => "8"]);
Track::create(["name" => "The Ocean", "duration" => "271098", "album_id" => "8"]);
Track::create(["name" => "In The Evening", "duration" => "410566", "album_id" => "9"]);
Track::create(["name" => "South Bound Saurez", "duration" => "254406", "album_id" => "9"]);
Track::create(["name" => "Fool In The Rain", "duration" => "372950", "album_id" => "9"]);
Track::create(["name" => "Hot Dog", "duration" => "197198", "album_id" => "9"]);
Track::create(["name" => "Carouselambra", "duration" => "634435", "album_id" => "9"]);
Track::create(["name" => "All My Love", "duration" => "356284", "album_id" => "9"]);
Track::create(["name" => "I'm Gonna Crawl", "duration" => "329639", "album_id" => "9"]);
Track::create(["name" => "Black Dog", "duration" => "296672", "album_id" => "10"]);
Track::create(["name" => "Rock & Roll", "duration" => "220917", "album_id" => "10"]);
Track::create(["name" => "The Battle Of Evermore", "duration" => "351555", "album_id" => "10"]);
Track::create(["name" => "Stairway To Heaven", "duration" => "481619", "album_id" => "10"]);
Track::create(["name" => "Misty Mountain Hop", "duration" => "278857", "album_id" => "10"]);
Track::create(["name" => "Four Sticks", "duration" => "284447", "album_id" => "10"]);
Track::create(["name" => "Going To California", "duration" => "215693", "album_id" => "10"]);
Track::create(["name" => "When The Levee Breaks", "duration" => "427702", "album_id" => "10"]);
Track::create(["name" => "Good Times Bad Times", "duration" => "166164", "album_id" => "11"]);
Track::create(["name" => "Babe I'm Gonna Leave You", "duration" => "401475", "album_id" => "11"]);
Track::create(["name" => "You Shook Me", "duration" => "388179", "album_id" => "11"]);
Track::create(["name" => "Dazed and Confused", "duration" => "386063", "album_id" => "11"]);
Track::create(["name" => "Your Time Is Gonna Come", "duration" => "274860", "album_id" => "11"]);
Track::create(["name" => "Black Mountain Side", "duration" => "132702", "album_id" => "11"]);
Track::create(["name" => "Communication Breakdown", "duration" => "150230", "album_id" => "11"]);
Track::create(["name" => "I Can't Quit You Baby", "duration" => "282671", "album_id" => "11"]);
Track::create(["name" => "How Many More Times", "duration" => "508055", "album_id" => "11"]);
Track::create(["name" => "Whole Lotta Love", "duration" => "334471", "album_id" => "12"]);
Track::create(["name" => "What Is And What Should Never Be", "duration" => "287973", "album_id" => "12"]);
Track::create(["name" => "The Lemon Song", "duration" => "379141", "album_id" => "12"]);
Track::create(["name" => "Thank You", "duration" => "287791", "album_id" => "12"]);
Track::create(["name" => "Heartbreaker", "duration" => "253988", "album_id" => "12"]);
Track::create(["name" => "Living Loving Maid (She's Just A Woman)", "duration" => "159216", "album_id" => "12"]);
Track::create(["name" => "Ramble On", "duration" => "275591", "album_id" => "12"]);
Track::create(["name" => "Moby Dick", "duration" => "260728", "album_id" => "12"]);
Track::create(["name" => "Bring It On Home", "duration" => "259970", "album_id" => "12"]);
Track::create(["name" => "Immigrant Song", "duration" => "144875", "album_id" => "13"]);
Track::create(["name" => "Friends", "duration" => "233560", "album_id" => "13"]);
Track::create(["name" => "Celebration Day", "duration" => "209528", "album_id" => "13"]);
Track::create(["name" => "Since I've Been Loving You", "duration" => "444055", "album_id" => "13"]);
Track::create(["name" => "Out On The Tiles", "duration" => "246047", "album_id" => "13"]);
Track::create(["name" => "Gallows Pole", "duration" => "296228", "album_id" => "13"]);
Track::create(["name" => "Tangerine", "duration" => "189675", "album_id" => "13"]);
Track::create(["name" => "That's The Way", "duration" => "337345", "album_id" => "13"]);
Track::create(["name" => "Bron-Y-Aur Stomp", "duration" => "259500", "album_id" => "13"]);
Track::create(["name" => "Hats Off To (Roy) Harper", "duration" => "219376", "album_id" => "13"]);
Track::create(["name" => "In The Light", "duration" => "526785", "album_id" => "14"]);
Track::create(["name" => "Bron-Yr-Aur", "duration" => "126641", "album_id" => "14"]);
Track::create(["name" => "Down By The Seaside", "duration" => "316186", "album_id" => "14"]);
Track::create(["name" => "Ten Years Gone", "duration" => "393116", "album_id" => "14"]);
Track::create(["name" => "Night Flight", "duration" => "217547", "album_id" => "14"]);
Track::create(["name" => "The Wanton Song", "duration" => "249887", "album_id" => "14"]);
Track::create(["name" => "Boogie With Stu", "duration" => "233273", "album_id" => "14"]);
Track::create(["name" => "Black Country Woman", "duration" => "273084", "album_id" => "14"]);
Track::create(["name" => "Sick Again", "duration" => "283036", "album_id" => "14"]);
Track::create(["name" => "Achilles Last Stand", "duration" => "625502", "album_id" => "15"]);
Track::create(["name" => "For Your Life", "duration" => "384391", "album_id" => "15"]);
Track::create(["name" => "Royal Orleans", "duration" => "179591", "album_id" => "15"]);
Track::create(["name" => "Nobody's Fault But Mine", "duration" => "376215", "album_id" => "15"]);
Track::create(["name" => "Candy Store Rock", "duration" => "252055", "album_id" => "15"]);
Track::create(["name" => "Hots On For Nowhere", "duration" => "284107", "album_id" => "15"]);
Track::create(["name" => "Tea For One", "duration" => "566752", "album_id" => "15"]);
Track::create(["name" => "Rock & Roll", "duration" => "242442", "album_id" => "16"]);
Track::create(["name" => "Celebration Day", "duration" => "230034", "album_id" => "16"]);
Track::create(["name" => "The Song Remains The Same", "duration" => "353358", "album_id" => "16"]);
Track::create(["name" => "Rain Song", "duration" => "505808", "album_id" => "16"]);
Track::create(["name" => "Dazed And Confused", "duration" => "1612329", "album_id" => "16"]);
Track::create(["name" => "No Quarter", "duration" => "749897", "album_id" => "17"]);
Track::create(["name" => "Stairway To Heaven", "duration" => "657293", "album_id" => "17"]);
Track::create(["name" => "Moby Dick", "duration" => "766354", "album_id" => "17"]);
Track::create(["name" => "Whole Lotta Love", "duration" => "863895", "album_id" => "17"]);
Track::create(["name" => "Enter Sandman", "duration" => "332251", "album_id" => "19"]);
Track::create(["name" => "Sad But True", "duration" => "324754", "album_id" => "19"]);
Track::create(["name" => "Holier Than Thou", "duration" => "227892", "album_id" => "19"]);
Track::create(["name" => "The Unforgiven", "duration" => "387082", "album_id" => "19"]);
Track::create(["name" => "Wherever I May Roam", "duration" => "404323", "album_id" => "19"]);
Track::create(["name" => "Don't Tread On Me", "duration" => "240483", "album_id" => "19"]);
Track::create(["name" => "Through The Never", "duration" => "244375", "album_id" => "19"]);
Track::create(["name" => "Nothing Else Matters", "duration" => "388832", "album_id" => "19"]);
Track::create(["name" => "Of Wolf And Man", "duration" => "256835", "album_id" => "19"]);
Track::create(["name" => "The God That Failed", "duration" => "308610", "album_id" => "19"]);
Track::create(["name" => "My Friend Of Misery", "duration" => "409547", "album_id" => "19"]);
Track::create(["name" => "The Struggle Within", "duration" => "234240", "album_id" => "19"]);
Track::create(["name" => "Helpless", "duration" => "398315", "album_id" => "20"]);
Track::create(["name" => "The Small Hours", "duration" => "403435", "album_id" => "20"]);
Track::create(["name" => "The Wait", "duration" => "295418", "album_id" => "20"]);
Track::create(["name" => "Crash Course In Brain Surgery", "duration" => "190406", "album_id" => "20"]);
Track::create(["name" => "Last Caress/Green Hell", "duration" => "209972", "album_id" => "20"]);
Track::create(["name" => "Am I Evil?", "duration" => "470256", "album_id" => "20"]);
Track::create(["name" => "Blitzkrieg", "duration" => "216685", "album_id" => "20"]);
Track::create(["name" => "Breadfan", "duration" => "341551", "album_id" => "20"]);
Track::create(["name" => "The Prince", "duration" => "265769", "album_id" => "20"]);
Track::create(["name" => "Stone Cold Crazy", "duration" => "137717", "album_id" => "20"]);
Track::create(["name" => "So What", "duration" => "189152", "album_id" => "20"]);
Track::create(["name" => "Killing Time", "duration" => "183693", "album_id" => "20"]);
Track::create(["name" => "Overkill", "duration" => "245133", "album_id" => "20"]);
Track::create(["name" => "Damage Case", "duration" => "220212", "album_id" => "20"]);
Track::create(["name" => "Stone Dead Forever", "duration" => "292127", "album_id" => "20"]);
Track::create(["name" => "Too Late Too Late", "duration" => "192052", "album_id" => "20"]);
Track::create(["name" => "Hit The Lights", "duration" => "257541", "album_id" => "21"]);
Track::create(["name" => "The Four Horsemen", "duration" => "433188", "album_id" => "21"]);
Track::create(["name" => "Motorbreath", "duration" => "188395", "album_id" => "21"]);
Track::create(["name" => "Jump In The Fire", "duration" => "281573", "album_id" => "21"]);
Track::create(["name" => "(Anesthesia) Pulling Teeth", "duration" => "254955", "album_id" => "21"]);
Track::create(["name" => "Whiplash", "duration" => "249208", "album_id" => "21"]);
Track::create(["name" => "Phantom Lord", "duration" => "302053", "album_id" => "21"]);
Track::create(["name" => "No Remorse", "duration" => "386795", "album_id" => "21"]);
Track::create(["name" => "Seek & Destroy", "duration" => "415817", "album_id" => "21"]);
Track::create(["name" => "Metal Militia", "duration" => "311327", "album_id" => "21"]);
Track::create(["name" => "Ain't My Bitch", "duration" => "304457", "album_id" => "22"]);
Track::create(["name" => "2 X 4", "duration" => "328254", "album_id" => "22"]);
Track::create(["name" => "The House Jack Built", "duration" => "398942", "album_id" => "22"]);
Track::create(["name" => "Until It Sleeps", "duration" => "269740", "album_id" => "22"]);
Track::create(["name" => "King Nothing", "duration" => "328097", "album_id" => "22"]);
Track::create(["name" => "Hero Of The Day", "duration" => "261982", "album_id" => "22"]);
Track::create(["name" => "Bleeding Me", "duration" => "497998", "album_id" => "22"]);
Track::create(["name" => "Cure", "duration" => "294347", "album_id" => "22"]);
Track::create(["name" => "Poor Twisted Me", "duration" => "240065", "album_id" => "22"]);
Track::create(["name" => "Wasted My Hate", "duration" => "237296", "album_id" => "22"]);
Track::create(["name" => "Mama Said", "duration" => "319764", "album_id" => "22"]);
Track::create(["name" => "Thorn Within", "duration" => "351738", "album_id" => "22"]);
Track::create(["name" => "Ronnie", "duration" => "317204", "album_id" => "22"]);
Track::create(["name" => "The Outlaw Torn", "duration" => "588721", "album_id" => "22"]);
Track::create(["name" => "Battery", "duration" => "312424", "album_id" => "23"]);
Track::create(["name" => "Master Of Puppets", "duration" => "515239", "album_id" => "23"]);
Track::create(["name" => "The Thing That Should Not Be", "duration" => "396199", "album_id" => "23"]);
Track::create(["name" => "Welcome Home (Sanitarium)", "duration" => "387186", "album_id" => "23"]);
Track::create(["name" => "Disposable Heroes", "duration" => "496718", "album_id" => "23"]);
Track::create(["name" => "Leper Messiah", "duration" => "347428", "album_id" => "23"]);
Track::create(["name" => "Orion", "duration" => "500062", "album_id" => "23"]);
Track::create(["name" => "Damage Inc.", "duration" => "330919", "album_id" => "23"]);
Track::create(["name" => "Fuel", "duration" => "269557", "album_id" => "24"]);
Track::create(["name" => "The Memory Remains", "duration" => "279353", "album_id" => "24"]);
Track::create(["name" => "Devil's Dance", "duration" => "318955", "album_id" => "24"]);
Track::create(["name" => "The Unforgiven II", "duration" => "395520", "album_id" => "24"]);
Track::create(["name" => "Better Than You", "duration" => "322899", "album_id" => "24"]);
Track::create(["name" => "Slither", "duration" => "313103", "album_id" => "24"]);
Track::create(["name" => "Carpe Diem Baby", "duration" => "372480", "album_id" => "24"]);
Track::create(["name" => "Bad Seed", "duration" => "245394", "album_id" => "24"]);
Track::create(["name" => "Where The Wild Things Are", "duration" => "414380", "album_id" => "24"]);
Track::create(["name" => "Prince Charming", "duration" => "365061", "album_id" => "24"]);
Track::create(["name" => "Low Man's Lyric", "duration" => "457639", "album_id" => "24"]);
Track::create(["name" => "Attitude", "duration" => "315898", "album_id" => "24"]);
Track::create(["name" => "Fixxxer", "duration" => "496065", "album_id" => "24"]);
Track::create(["name" => "Fight Fire With Fire", "duration" => "285753", "album_id" => "25"]);
Track::create(["name" => "Ride The Lightning", "duration" => "397740", "album_id" => "25"]);
Track::create(["name" => "For Whom The Bell Tolls", "duration" => "311719", "album_id" => "25"]);
Track::create(["name" => "Fade To Black", "duration" => "414824", "album_id" => "25"]);
Track::create(["name" => "Trapped Under Ice", "duration" => "244532", "album_id" => "25"]);
Track::create(["name" => "Escape", "duration" => "264359", "album_id" => "25"]);
Track::create(["name" => "Creeping Death", "duration" => "396878", "album_id" => "25"]);
Track::create(["name" => "The Call Of Ktulu", "duration" => "534883", "album_id" => "25"]);
Track::create(["name" => "Frantic", "duration" => "350458", "album_id" => "26"]);
Track::create(["name" => "St. Anger", "duration" => "441234", "album_id" => "26"]);
Track::create(["name" => "Some Kind Of Monster", "duration" => "505626", "album_id" => "26"]);
Track::create(["name" => "Dirty Window", "duration" => "324989", "album_id" => "26"]);
Track::create(["name" => "Invisible Kid", "duration" => "510197", "album_id" => "26"]);
Track::create(["name" => "My World", "duration" => "345626", "album_id" => "26"]);
Track::create(["name" => "Shoot Me Again", "duration" => "430210", "album_id" => "26"]);
Track::create(["name" => "Sweet Amber", "duration" => "327235", "album_id" => "26"]);
Track::create(["name" => "The Unnamed Feeling", "duration" => "429479", "album_id" => "26"]);
Track::create(["name" => "Purify", "duration" => "314017", "album_id" => "26"]);
Track::create(["name" => "All Within My Hands", "duration" => "527986", "album_id" => "26"]);
Track::create(["name" => "Blackened", "duration" => "403382", "album_id" => "27"]);
Track::create(["name" => "...And Justice For All", "duration" => "585769", "album_id" => "27"]);
Track::create(["name" => "Eye Of The Beholder", "duration" => "385828", "album_id" => "27"]);
Track::create(["name" => "One", "duration" => "446484", "album_id" => "27"]);
Track::create(["name" => "The Shortest Straw", "duration" => "395389", "album_id" => "27"]);
Track::create(["name" => "Harvester Of Sorrow", "duration" => "345547", "album_id" => "27"]);
Track::create(["name" => "The Frayed Ends Of Sanity", "duration" => "464039", "album_id" => "27"]);
Track::create(["name" => "To Live Is To Die", "duration" => "588564", "album_id" => "27"]);
Track::create(["name" => "Dyers Eve", "duration" => "313991", "album_id" => "27"]);
Track::create(["name" => "Intro", "duration" => "52218", "album_id" => "45"]);
Track::create(["name" => "School", "duration" => "160235", "album_id" => "45"]);
Track::create(["name" => "Drain You", "duration" => "215196", "album_id" => "45"]);
Track::create(["name" => "Aneurysm", "duration" => "271516", "album_id" => "45"]);
Track::create(["name" => "Smells Like Teen Spirit", "duration" => "287190", "album_id" => "45"]);
Track::create(["name" => "Been A Son", "duration" => "127555", "album_id" => "45"]);
Track::create(["name" => "Lithium", "duration" => "250017", "album_id" => "45"]);
Track::create(["name" => "Sliver", "duration" => "116218", "album_id" => "45"]);
Track::create(["name" => "Spank Thru", "duration" => "190354", "album_id" => "45"]);
Track::create(["name" => "Scentless Apprentice", "duration" => "211200", "album_id" => "45"]);
Track::create(["name" => "Heart-Shaped Box", "duration" => "281887", "album_id" => "45"]);
Track::create(["name" => "Milk It", "duration" => "225724", "album_id" => "45"]);
Track::create(["name" => "Negative Creep", "duration" => "163761", "album_id" => "45"]);
Track::create(["name" => "Polly", "duration" => "149995", "album_id" => "45"]);
Track::create(["name" => "Breed", "duration" => "208378", "album_id" => "45"]);
Track::create(["name" => "Tourette's", "duration" => "115591", "album_id" => "45"]);
Track::create(["name" => "Blew", "duration" => "216346", "album_id" => "45"]);
Track::create(["name" => "Smells Like Teen Spirit", "duration" => "301296", "album_id" => "46"]);
Track::create(["name" => "In Bloom", "duration" => "254928", "album_id" => "46"]);
Track::create(["name" => "Come As You Are", "duration" => "219219", "album_id" => "46"]);
Track::create(["name" => "Breed", "duration" => "183928", "album_id" => "46"]);
Track::create(["name" => "Lithium", "duration" => "256992", "album_id" => "46"]);
Track::create(["name" => "Polly", "duration" => "177031", "album_id" => "46"]);
Track::create(["name" => "Territorial Pissings", "duration" => "143281", "album_id" => "46"]);
Track::create(["name" => "Drain You", "duration" => "223973", "album_id" => "46"]);
Track::create(["name" => "Lounge Act", "duration" => "156786", "album_id" => "46"]);
Track::create(["name" => "Stay Away", "duration" => "212636", "album_id" => "46"]);
Track::create(["name" => "On A Plain", "duration" => "196440", "album_id" => "46"]);
Track::create(["name" => "Something In The Way", "duration" => "230556", "album_id" => "46"]);
Track::create(["name" => "Corduroy", "duration" => "305293", "album_id" => "47"]);
Track::create(["name" => "Given To Fly", "duration" => "233613", "album_id" => "47"]);
Track::create(["name" => "Hail, Hail", "duration" => "223764", "album_id" => "47"]);
Track::create(["name" => "Daughter", "duration" => "407484", "album_id" => "47"]);
Track::create(["name" => "Elderly Woman Behind The Counter In A Small Town", "duration" => "229328", "album_id" => "47"]);
Track::create(["name" => "Untitled", "duration" => "122801", "album_id" => "47"]);
Track::create(["name" => "MFC", "duration" => "148192", "album_id" => "47"]);
Track::create(["name" => "Go", "duration" => "161541", "album_id" => "47"]);
Track::create(["name" => "Red Mosquito", "duration" => "242991", "album_id" => "47"]);
Track::create(["name" => "Even Flow", "duration" => "317100", "album_id" => "47"]);
Track::create(["name" => "Off He Goes", "duration" => "343222", "album_id" => "47"]);
Track::create(["name" => "Nothingman", "duration" => "278595", "album_id" => "47"]);
Track::create(["name" => "Do The Evolution", "duration" => "225462", "album_id" => "47"]);
Track::create(["name" => "Better Man", "duration" => "246204", "album_id" => "47"]);
Track::create(["name" => "Black", "duration" => "415712", "album_id" => "47"]);
Track::create(["name" => "F*Ckin' Up", "duration" => "377652", "album_id" => "47"]);
Track::create(["name" => "Life Wasted", "duration" => "234344", "album_id" => "48"]);
Track::create(["name" => "World Wide Suicide", "duration" => "209188", "album_id" => "48"]);
Track::create(["name" => "Comatose", "duration" => "139990", "album_id" => "48"]);
Track::create(["name" => "Severed Hand", "duration" => "270341", "album_id" => "48"]);
Track::create(["name" => "Marker In The Sand", "duration" => "263235", "album_id" => "48"]);
Track::create(["name" => "Parachutes", "duration" => "216555", "album_id" => "48"]);
Track::create(["name" => "Unemployable", "duration" => "184398", "album_id" => "48"]);
Track::create(["name" => "Big Wave", "duration" => "178573", "album_id" => "48"]);
Track::create(["name" => "Gone", "duration" => "249547", "album_id" => "48"]);
Track::create(["name" => "Wasted Reprise", "duration" => "53733", "album_id" => "48"]);
Track::create(["name" => "Army Reserve", "duration" => "225567", "album_id" => "48"]);
Track::create(["name" => "Come Back", "duration" => "329743", "album_id" => "48"]);
Track::create(["name" => "Inside Job", "duration" => "428643", "album_id" => "48"]);
Track::create(["name" => "Can't Keep", "duration" => "219428", "album_id" => "49"]);
Track::create(["name" => "Save You", "duration" => "230112", "album_id" => "49"]);
Track::create(["name" => "Love Boat Captain", "duration" => "276453", "album_id" => "49"]);
Track::create(["name" => "Cropduster", "duration" => "231888", "album_id" => "49"]);
Track::create(["name" => "Ghost", "duration" => "195108", "album_id" => "49"]);
Track::create(["name" => "I Am Mine", "duration" => "215719", "album_id" => "49"]);
Track::create(["name" => "Thumbing My Way", "duration" => "250226", "album_id" => "49"]);
Track::create(["name" => "You Are", "duration" => "270863", "album_id" => "49"]);
Track::create(["name" => "Get Right", "duration" => "158589", "album_id" => "49"]);
Track::create(["name" => "Green Disease", "duration" => "161253", "album_id" => "49"]);
Track::create(["name" => "Help Help", "duration" => "215092", "album_id" => "49"]);
Track::create(["name" => "Bushleager", "duration" => "237479", "album_id" => "49"]);
Track::create(["name" => "1/2 Full", "duration" => "251010", "album_id" => "49"]);
Track::create(["name" => "Arc", "duration" => "65593", "album_id" => "49"]);
Track::create(["name" => "All or None", "duration" => "277655", "album_id" => "49"]);
Track::create(["name" => "Once", "duration" => "231758", "album_id" => "50"]);
Track::create(["name" => "Evenflow", "duration" => "293720", "album_id" => "50"]);
Track::create(["name" => "Alive", "duration" => "341080", "album_id" => "50"]);
Track::create(["name" => "Why Go", "duration" => "200254", "album_id" => "50"]);
Track::create(["name" => "Black", "duration" => "343823", "album_id" => "50"]);
Track::create(["name" => "Jeremy", "duration" => "318981", "album_id" => "50"]);
Track::create(["name" => "Oceans", "duration" => "162194", "album_id" => "50"]);
Track::create(["name" => "Porch", "duration" => "210520", "album_id" => "50"]);
Track::create(["name" => "Garden", "duration" => "299154", "album_id" => "50"]);
Track::create(["name" => "Deep", "duration" => "258324", "album_id" => "50"]);
Track::create(["name" => "Release", "duration" => "546063", "album_id" => "50"]);
Track::create(["name" => "Go", "duration" => "193123", "album_id" => "51"]);
Track::create(["name" => "Animal", "duration" => "169325", "album_id" => "51"]);
Track::create(["name" => "Daughter", "duration" => "235598", "album_id" => "51"]);
Track::create(["name" => "Glorified G", "duration" => "206968", "album_id" => "51"]);
Track::create(["name" => "Dissident", "duration" => "215510", "album_id" => "51"]);
Track::create(["name" => "W.M.A.", "duration" => "359262", "album_id" => "51"]);
Track::create(["name" => "Blood", "duration" => "170631", "album_id" => "51"]);
Track::create(["name" => "Rearviewmirror", "duration" => "284186", "album_id" => "51"]);
Track::create(["name" => "Rats", "duration" => "255425", "album_id" => "51"]);
Track::create(["name" => "Elderly Woman Behind The Counter In A Small Town", "duration" => "196336", "album_id" => "51"]);
Track::create(["name" => "Leash", "duration" => "189257", "album_id" => "51"]);
Track::create(["name" => "Indifference", "duration" => "302053", "album_id" => "51"]);
Track::create(["name" => "Bohemian Rhapsody", "duration" => "358948", "album_id" => "29"]);
Track::create(["name" => "Another One Bites The Dust", "duration" => "216946", "album_id" => "29"]);
Track::create(["name" => "Killer Queen", "duration" => "182099", "album_id" => "29"]);
Track::create(["name" => "Fat Bottomed Girls", "duration" => "204695", "album_id" => "29"]);
Track::create(["name" => "Bicycle Race", "duration" => "183823", "album_id" => "29"]);
Track::create(["name" => "You're My Best Friend", "duration" => "172225", "album_id" => "29"]);
Track::create(["name" => "Don't Stop Me Now", "duration" => "211826", "album_id" => "29"]);
Track::create(["name" => "Save Me", "duration" => "228832", "album_id" => "29"]);
Track::create(["name" => "Crazy Little Thing Called Love", "duration" => "164231", "album_id" => "29"]);
Track::create(["name" => "Somebody To Love", "duration" => "297351", "album_id" => "29"]);
Track::create(["name" => "Now I'm Here", "duration" => "255346", "album_id" => "29"]);
Track::create(["name" => "Good Old-Fashioned Lover Boy", "duration" => "175960", "album_id" => "29"]);
Track::create(["name" => "Play The Game", "duration" => "213368", "album_id" => "29"]);
Track::create(["name" => "Flash", "duration" => "168489", "album_id" => "29"]);
Track::create(["name" => "Seven Seas Of Rhye", "duration" => "170553", "album_id" => "29"]);
Track::create(["name" => "We Will Rock You", "duration" => "122880", "album_id" => "29"]);
Track::create(["name" => "We Are The Champions", "duration" => "180950", "album_id" => "29"]);
Track::create(["name" => "We Will Rock You", "duration" => "122671", "album_id" => "30"]);
Track::create(["name" => "We Are The Champions", "duration" => "182883", "album_id" => "30"]);
Track::create(["name" => "Sheer Heart Attack", "duration" => "207386", "album_id" => "30"]);
Track::create(["name" => "All Dead, All Dead", "duration" => "190119", "album_id" => "30"]);
Track::create(["name" => "Spread Your Wings", "duration" => "275356", "album_id" => "30"]);
Track::create(["name" => "Fight From The Inside", "duration" => "184737", "album_id" => "30"]);
Track::create(["name" => "Get Down, Make Love", "duration" => "231235", "album_id" => "30"]);
Track::create(["name" => "Sleep On The Sidewalk", "duration" => "187428", "album_id" => "30"]);
Track::create(["name" => "Who Needs You", "duration" => "186958", "album_id" => "30"]);
Track::create(["name" => "It's Late", "duration" => "386194", "album_id" => "30"]);
Track::create(["name" => "My Melancholy Blues", "duration" => "206471", "album_id" => "30"]);
Track::create(["name" => "The Power Of Equality", "duration" => "243591", "album_id" => "52"]);
Track::create(["name" => "If You Have To Ask", "duration" => "216790", "album_id" => "52"]);
Track::create(["name" => "Breaking The Girl", "duration" => "295497", "album_id" => "52"]);
Track::create(["name" => "Funky Monks", "duration" => "323395", "album_id" => "52"]);
Track::create(["name" => "Suck My Kiss", "duration" => "217234", "album_id" => "52"]);
Track::create(["name" => "I Could Have Lied", "duration" => "244506", "album_id" => "52"]);
Track::create(["name" => "Mellowship Slinky In B Major", "duration" => "240091", "album_id" => "52"]);
Track::create(["name" => "The Righteous & The Wicked", "duration" => "248084", "album_id" => "52"]);
Track::create(["name" => "Give It Away", "duration" => "283010", "album_id" => "52"]);
Track::create(["name" => "Blood Sugar Sex Magik", "duration" => "271229", "album_id" => "52"]);
Track::create(["name" => "Under The Bridge", "duration" => "264359", "album_id" => "52"]);
Track::create(["name" => "Naked In The Rain", "duration" => "265717", "album_id" => "52"]);
Track::create(["name" => "Apache Rose Peacock", "duration" => "282226", "album_id" => "52"]);
Track::create(["name" => "The Greeting Song", "duration" => "193593", "album_id" => "52"]);
Track::create(["name" => "My Lovely Man", "duration" => "279118", "album_id" => "52"]);
Track::create(["name" => "Sir Psycho Sexy", "duration" => "496692", "album_id" => "52"]);
Track::create(["name" => "They're Red Hot", "duration" => "71941", "album_id" => "52"]);
Track::create(["name" => "By The Way", "duration" => "218017", "album_id" => "53"]);
Track::create(["name" => "Universally Speaking", "duration" => "259213", "album_id" => "53"]);
Track::create(["name" => "This Is The Place", "duration" => "257906", "album_id" => "53"]);
Track::create(["name" => "Dosed", "duration" => "312058", "album_id" => "53"]);
Track::create(["name" => "Don't Forget Me", "duration" => "277995", "album_id" => "53"]);
Track::create(["name" => "The Zephyr Song", "duration" => "232960", "album_id" => "53"]);
Track::create(["name" => "Can't Stop", "duration" => "269400", "album_id" => "53"]);
Track::create(["name" => "I Could Die For You", "duration" => "193906", "album_id" => "53"]);
Track::create(["name" => "Midnight", "duration" => "295810", "album_id" => "53"]);
Track::create(["name" => "Throw Away Your Television", "duration" => "224574", "album_id" => "53"]);
Track::create(["name" => "Cabron", "duration" => "218592", "album_id" => "53"]);
Track::create(["name" => "Tear", "duration" => "317413", "album_id" => "53"]);
Track::create(["name" => "On Mercury", "duration" => "208509", "album_id" => "53"]);
Track::create(["name" => "Minor Thing", "duration" => "217835", "album_id" => "53"]);
Track::create(["name" => "Warm Tape", "duration" => "256653", "album_id" => "53"]);
Track::create(["name" => "Venice Queen", "duration" => "369110", "album_id" => "53"]);
Track::create(["name" => "Around The World", "duration" => "238837", "album_id" => "54"]);
Track::create(["name" => "Parallel Universe", "duration" => "270654", "album_id" => "54"]);
Track::create(["name" => "Scar Tissue", "duration" => "217469", "album_id" => "54"]);
Track::create(["name" => "Otherside", "duration" => "255973", "album_id" => "54"]);
Track::create(["name" => "Get On Top", "duration" => "198164", "album_id" => "54"]);
Track::create(["name" => "Californication", "duration" => "321671", "album_id" => "54"]);
Track::create(["name" => "Easily", "duration" => "231418", "album_id" => "54"]);
Track::create(["name" => "Porcelain", "duration" => "163787", "album_id" => "54"]);
Track::create(["name" => "Emit Remmus", "duration" => "240300", "album_id" => "54"]);
Track::create(["name" => "I Like Dirt", "duration" => "157727", "album_id" => "54"]);
Track::create(["name" => "This Velvet Glove", "duration" => "225280", "album_id" => "54"]);
Track::create(["name" => "Savior", "duration" => "292493", "album_id" => "54"]);
Track::create(["name" => "Purple Stain", "duration" => "253440", "album_id" => "54"]);
Track::create(["name" => "Right On Time", "duration" => "112613", "album_id" => "54"]);
Track::create(["name" => "Road Trippin'", "duration" => "205635", "album_id" => "54"]);
Track::create(["name" => "Lucky 13", "duration" => "189387", "album_id" => "55"]);
Track::create(["name" => "Aeroplane Flies High", "duration" => "473391", "album_id" => "55"]);
Track::create(["name" => "Because You Are", "duration" => "226403", "album_id" => "55"]);
Track::create(["name" => "Slow Dawn", "duration" => "192339", "album_id" => "55"]);
Track::create(["name" => "Believe", "duration" => "192940", "album_id" => "55"]);
Track::create(["name" => "My Mistake", "duration" => "240901", "album_id" => "55"]);
Track::create(["name" => "Marquis In Spades", "duration" => "192731", "album_id" => "55"]);
Track::create(["name" => "Here's To The Atom Bomb", "duration" => "266893", "album_id" => "55"]);
Track::create(["name" => "Sparrow", "duration" => "176822", "album_id" => "55"]);
Track::create(["name" => "Waiting", "duration" => "228336", "album_id" => "55"]);
Track::create(["name" => "Saturnine", "duration" => "229877", "album_id" => "55"]);
Track::create(["name" => "Rock On", "duration" => "366471", "album_id" => "55"]);
Track::create(["name" => "Set The Ray To Jerry", "duration" => "249364", "album_id" => "55"]);
Track::create(["name" => "Winterlong", "duration" => "299389", "album_id" => "55"]);
Track::create(["name" => "Soot & Stars", "duration" => "399986", "album_id" => "55"]);
Track::create(["name" => "Blissed & Gone", "duration" => "286302", "album_id" => "55"]);
Track::create(["name" => "Siva", "duration" => "261172", "album_id" => "56"]);
Track::create(["name" => "Rhinocerous", "duration" => "353462", "album_id" => "56"]);
Track::create(["name" => "Drown", "duration" => "270497", "album_id" => "56"]);
Track::create(["name" => "Cherub Rock", "duration" => "299389", "album_id" => "56"]);
Track::create(["name" => "Today", "duration" => "202213", "album_id" => "56"]);
Track::create(["name" => "Disarm", "duration" => "198556", "album_id" => "56"]);
Track::create(["name" => "Landslide", "duration" => "190275", "album_id" => "56"]);
Track::create(["name" => "Bullet With Butterfly Wings", "duration" => "257306", "album_id" => "56"]);
Track::create(["name" => "1979", "duration" => "263653", "album_id" => "56"]);
Track::create(["name" => "Zero", "duration" => "161123", "album_id" => "56"]);
Track::create(["name" => "Tonight, Tonight", "duration" => "255686", "album_id" => "56"]);
Track::create(["name" => "Eye", "duration" => "294530", "album_id" => "56"]);
Track::create(["name" => "Ava Adore", "duration" => "261433", "album_id" => "56"]);
Track::create(["name" => "Perfect", "duration" => "203023", "album_id" => "56"]);
Track::create(["name" => "The Everlasting Gaze", "duration" => "242155", "album_id" => "56"]);
Track::create(["name" => "Stand Inside Your Love", "duration" => "253753", "album_id" => "56"]);
Track::create(["name" => "Real Love", "duration" => "250697", "album_id" => "56"]);
Track::create(["name" => "[Untitled]", "duration" => "231784", "album_id" => "56"]);
Track::create(["name" => "Nothing To Say", "duration" => "238027", "album_id" => "57"]);
Track::create(["name" => "Flower", "duration" => "208822", "album_id" => "57"]);
Track::create(["name" => "Loud Love", "duration" => "297456", "album_id" => "57"]);
Track::create(["name" => "Hands All Over", "duration" => "362475", "album_id" => "57"]);
Track::create(["name" => "Get On The Snake", "duration" => "225123", "album_id" => "57"]);
Track::create(["name" => "Jesus Christ Pose", "duration" => "352966", "album_id" => "57"]);
Track::create(["name" => "Outshined", "duration" => "312476", "album_id" => "57"]);
Track::create(["name" => "Rusty Cage", "duration" => "267728", "album_id" => "57"]);
Track::create(["name" => "Spoonman", "duration" => "248476", "album_id" => "57"]);
Track::create(["name" => "The Day I Tried To Live", "duration" => "321175", "album_id" => "57"]);
Track::create(["name" => "Black Hole Sun", "duration" => "320365", "album_id" => "57"]);
Track::create(["name" => "Fell On Black Days", "duration" => "282331", "album_id" => "57"]);
Track::create(["name" => "Pretty Noose", "duration" => "253570", "album_id" => "57"]);
Track::create(["name" => "Burden In My Hand", "duration" => "292153", "album_id" => "57"]);
Track::create(["name" => "Blow Up The Outside World", "duration" => "347898", "album_id" => "57"]);
Track::create(["name" => "Ty Cobb", "duration" => "188786", "album_id" => "57"]);
Track::create(["name" => "Bleed Together", "duration" => "232202", "album_id" => "57"]);
Track::create(["name" => "Dead And Bloated", "duration" => "310386", "album_id" => "58"]);
Track::create(["name" => "Sex Type Thing", "duration" => "218723", "album_id" => "58"]);
Track::create(["name" => "Wicked Garden", "duration" => "245368", "album_id" => "58"]);
Track::create(["name" => "No Memory", "duration" => "80613", "album_id" => "58"]);
Track::create(["name" => "Sin", "duration" => "364800", "album_id" => "58"]);
Track::create(["name" => "Naked Sunday", "duration" => "229720", "album_id" => "58"]);
Track::create(["name" => "Creep", "duration" => "333191", "album_id" => "58"]);
Track::create(["name" => "Piece Of Pie", "duration" => "324623", "album_id" => "58"]);
Track::create(["name" => "Plush", "duration" => "314017", "album_id" => "58"]);
Track::create(["name" => "Wet My Bed", "duration" => "96914", "album_id" => "58"]);
Track::create(["name" => "Crackerman", "duration" => "194403", "album_id" => "58"]);
Track::create(["name" => "Where The River Goes", "duration" => "505991", "album_id" => "58"]);
Track::create(["name" => "Soldier Side - Intro", "duration" => "63764", "album_id" => "59"]);
Track::create(["name" => "B.Y.O.B.", "duration" => "255555", "album_id" => "59"]);
Track::create(["name" => "Revenga", "duration" => "228127", "album_id" => "59"]);
Track::create(["name" => "Cigaro", "duration" => "131787", "album_id" => "59"]);
Track::create(["name" => "Radio/Video", "duration" => "249312", "album_id" => "59"]);
Track::create(["name" => "This Cocaine Makes Me Feel Like I'm On This Song", "duration" => "128339", "album_id" => "59"]);
Track::create(["name" => "Violent Pornography", "duration" => "211435", "album_id" => "59"]);
Track::create(["name" => "Question!", "duration" => "200698", "album_id" => "59"]);
Track::create(["name" => "Sad Statue", "duration" => "205897", "album_id" => "59"]);
Track::create(["name" => "Old School Hollywood", "duration" => "176953", "album_id" => "59"]);
Track::create(["name" => "Lost in Hollywood", "duration" => "320783", "album_id" => "59"]);
Track::create(["name" => "Break on Through", "duration" => "149342", "album_id" => "60"]);
Track::create(["name" => "Soul Kitchen", "duration" => "215066", "album_id" => "60"]);
Track::create(["name" => "The Crystal Ship", "duration" => "154853", "album_id" => "60"]);
Track::create(["name" => "Twentienth Century Fox", "duration" => "153913", "album_id" => "60"]);
Track::create(["name" => "Alabama Song", "duration" => "200097", "album_id" => "60"]);
Track::create(["name" => "Light My Fire", "duration" => "428329", "album_id" => "60"]);
Track::create(["name" => "Back Door Man", "duration" => "214360", "album_id" => "60"]);
Track::create(["name" => "I Looked At You", "duration" => "142080", "album_id" => "60"]);
Track::create(["name" => "End Of The Night", "duration" => "172695", "album_id" => "60"]);
Track::create(["name" => "Take It As It Comes", "duration" => "137168", "album_id" => "60"]);
Track::create(["name" => "The End", "duration" => "701831", "album_id" => "60"]);
Track::create(["name" => "Roxanne", "duration" => "192992", "album_id" => "61"]);
Track::create(["name" => "Can't Stand Losing You", "duration" => "181159", "album_id" => "61"]);
Track::create(["name" => "Message in a Bottle", "duration" => "291474", "album_id" => "61"]);
Track::create(["name" => "Walking on the Moon", "duration" => "302080", "album_id" => "61"]);
Track::create(["name" => "Don't Stand so Close to Me", "duration" => "241031", "album_id" => "61"]);
Track::create(["name" => "De Do Do Do, De Da Da Da", "duration" => "247196", "album_id" => "61"]);
Track::create(["name" => "Every Little Thing She Does is Magic", "duration" => "261120", "album_id" => "61"]);
Track::create(["name" => "Invisible Sun", "duration" => "225593", "album_id" => "61"]);
Track::create(["name" => "Spirit's in the Material World", "duration" => "181133", "album_id" => "61"]);
Track::create(["name" => "Every Breath You Take", "duration" => "254615", "album_id" => "61"]);
Track::create(["name" => "King Of Pain", "duration" => "300512", "album_id" => "61"]);
Track::create(["name" => "Wrapped Around Your Finger", "duration" => "315454", "album_id" => "61"]);
Track::create(["name" => "Don't Stand So Close to Me '86", "duration" => "293590", "album_id" => "61"]);
Track::create(["name" => "Message in a Bottle (new classic rock mix)", "duration" => "290951", "album_id" => "61"]);
Track::create(["name" => "Time Is On My Side", "duration" => "179983", "album_id" => "62"]);
Track::create(["name" => "Heart Of Stone", "duration" => "164493", "album_id" => "62"]);
Track::create(["name" => "Play With Fire", "duration" => "132022", "album_id" => "62"]);
Track::create(["name" => "Satisfaction", "duration" => "226612", "album_id" => "62"]);
Track::create(["name" => "As Tears Go By", "duration" => "164284", "album_id" => "62"]);
Track::create(["name" => "Get Off Of My Cloud", "duration" => "176013", "album_id" => "62"]);
Track::create(["name" => "Mother's Little Helper", "duration" => "167549", "album_id" => "62"]);
Track::create(["name" => "19th Nervous Breakdown", "duration" => "237923", "album_id" => "62"]);
Track::create(["name" => "Paint It Black", "duration" => "226063", "album_id" => "62"]);
Track::create(["name" => "Under My Thumb", "duration" => "221387", "album_id" => "62"]);
Track::create(["name" => "Ruby Tuesday", "duration" => "197459", "album_id" => "62"]);
Track::create(["name" => "Let's Spend The Night Together", "duration" => "217495", "album_id" => "62"]);
Track::create(["name" => "Intro", "duration" => "49737", "album_id" => "63"]);
Track::create(["name" => "You Got Me Rocking", "duration" => "205766", "album_id" => "63"]);
Track::create(["name" => "Gimmie Shelters", "duration" => "382119", "album_id" => "63"]);
Track::create(["name" => "Flip The Switch", "duration" => "252421", "album_id" => "63"]);
Track::create(["name" => "Memory Motel", "duration" => "365844", "album_id" => "63"]);
Track::create(["name" => "Corinna", "duration" => "257488", "album_id" => "63"]);
Track::create(["name" => "Saint Of Me", "duration" => "325694", "album_id" => "63"]);
Track::create(["name" => "Wainting On A Friend", "duration" => "302497", "album_id" => "63"]);
Track::create(["name" => "Sister Morphine", "duration" => "376215", "album_id" => "63"]);
Track::create(["name" => "Live With Me", "duration" => "234893", "album_id" => "63"]);
Track::create(["name" => "Respectable", "duration" => "215693", "album_id" => "63"]);
Track::create(["name" => "Thief In The Night", "duration" => "337266", "album_id" => "63"]);
Track::create(["name" => "The Last Time", "duration" => "287294", "album_id" => "63"]);
Track::create(["name" => "Out Of Control", "duration" => "479242", "album_id" => "63"]);
Track::create(["name" => "Love Is Strong", "duration" => "230896", "album_id" => "64"]);
Track::create(["name" => "You Got Me Rocking", "duration" => "215928", "album_id" => "64"]);
Track::create(["name" => "Sparks Will Fly", "duration" => "196466", "album_id" => "64"]);
Track::create(["name" => "The Worst", "duration" => "144613", "album_id" => "64"]);
Track::create(["name" => "New Faces", "duration" => "172146", "album_id" => "64"]);
Track::create(["name" => "Moon Is Up", "duration" => "222119", "album_id" => "64"]);
Track::create(["name" => "Out Of Tears", "duration" => "327418", "album_id" => "64"]);
Track::create(["name" => "I Go Wild", "duration" => "264019", "album_id" => "64"]);
Track::create(["name" => "Brand New Car", "duration" => "256052", "album_id" => "64"]);
Track::create(["name" => "Sweethearts Together", "duration" => "285492", "album_id" => "64"]);
Track::create(["name" => "Suck On The Jugular", "duration" => "268225", "album_id" => "64"]);
Track::create(["name" => "Blinded By Rainbows", "duration" => "273946", "album_id" => "64"]);
Track::create(["name" => "Baby Break It Down", "duration" => "249417", "album_id" => "64"]);
Track::create(["name" => "Thru And Thru", "duration" => "375092", "album_id" => "64"]);
Track::create(["name" => "Mean Disposition", "duration" => "249155", "album_id" => "64"]);
Track::create(["name" => "Zoo Station", "duration" => "276349", "album_id" => "65"]);
Track::create(["name" => "Even Better Than The Real Thing", "duration" => "221361", "album_id" => "65"]);
Track::create(["name" => "One", "duration" => "276192", "album_id" => "65"]);
Track::create(["name" => "Until The End Of The World", "duration" => "278700", "album_id" => "65"]);
Track::create(["name" => "Who's Gonna Ride Your Wild Horses", "duration" => "316551", "album_id" => "65"]);
Track::create(["name" => "So Cruel", "duration" => "349492", "album_id" => "65"]);
Track::create(["name" => "The Fly", "duration" => "268982", "album_id" => "65"]);
Track::create(["name" => "Mysterious Ways", "duration" => "243826", "album_id" => "65"]);
Track::create(["name" => "Tryin' To Throw Your Arms Around The World", "duration" => "232463", "album_id" => "65"]);
Track::create(["name" => "Ultraviolet (Light My Way)", "duration" => "330788", "album_id" => "65"]);
Track::create(["name" => "Acrobat", "duration" => "270288", "album_id" => "65"]);
Track::create(["name" => "Love Is Blindness", "duration" => "263497", "album_id" => "65"]);
Track::create(["name" => "Beautiful Day", "duration" => "248163", "album_id" => "66"]);
Track::create(["name" => "Stuck In A Moment You Can't Get Out Of", "duration" => "272378", "album_id" => "66"]);
Track::create(["name" => "Elevation", "duration" => "227552", "album_id" => "66"]);
Track::create(["name" => "Walk On", "duration" => "296280", "album_id" => "66"]);
Track::create(["name" => "Kite", "duration" => "266893", "album_id" => "66"]);
Track::create(["name" => "In A Little While", "duration" => "219271", "album_id" => "66"]);
Track::create(["name" => "Wild Honey", "duration" => "226768", "album_id" => "66"]);
Track::create(["name" => "Peace On Earth", "duration" => "288496", "album_id" => "66"]);
Track::create(["name" => "When I Look At The World", "duration" => "257776", "album_id" => "66"]);
Track::create(["name" => "New York", "duration" => "330370", "album_id" => "66"]);
Track::create(["name" => "Grace", "duration" => "330657", "album_id" => "66"]);
Track::create(["name" => "The Three Sunrises", "duration" => "234788", "album_id" => "67"]);
Track::create(["name" => "Spanish Eyes", "duration" => "196702", "album_id" => "67"]);
Track::create(["name" => "Sweetest Thing", "duration" => "185103", "album_id" => "67"]);
Track::create(["name" => "Love Comes Tumbling", "duration" => "282671", "album_id" => "67"]);
Track::create(["name" => "Bass Trap", "duration" => "213289", "album_id" => "67"]);
Track::create(["name" => "Dancing Barefoot", "duration" => "287895", "album_id" => "67"]);
Track::create(["name" => "Everlasting Love", "duration" => "202631", "album_id" => "67"]);
Track::create(["name" => "Unchained Melody", "duration" => "294164", "album_id" => "67"]);
Track::create(["name" => "Walk To The Water", "duration" => "289253", "album_id" => "67"]);
Track::create(["name" => "Luminous Times (Hold On To Love)", "duration" => "277760", "album_id" => "67"]);
Track::create(["name" => "Hallelujah Here She Comes", "duration" => "242364", "album_id" => "67"]);
Track::create(["name" => "Silver And Gold", "duration" => "279875", "album_id" => "67"]);
Track::create(["name" => "Endless Deep", "duration" => "179879", "album_id" => "67"]);
Track::create(["name" => "A Room At The Heartbreak Hotel", "duration" => "274546", "album_id" => "67"]);
Track::create(["name" => "Trash, Trampoline And The Party Girl", "duration" => "153965", "album_id" => "67"]);
Track::create(["name" => "Vertigo", "duration" => "194612", "album_id" => "68"]);
Track::create(["name" => "Miracle Drug", "duration" => "239124", "album_id" => "68"]);
Track::create(["name" => "Sometimes You Can't Make It On Your Own", "duration" => "308976", "album_id" => "68"]);
Track::create(["name" => "Love And Peace Or Else", "duration" => "290690", "album_id" => "68"]);
Track::create(["name" => "City Of Blinding Lights", "duration" => "347951", "album_id" => "68"]);
Track::create(["name" => "All Because Of You", "duration" => "219141", "album_id" => "68"]);
Track::create(["name" => "A Man And A Woman", "duration" => "270132", "album_id" => "68"]);
Track::create(["name" => "Crumbs From Your Table", "duration" => "303568", "album_id" => "68"]);
Track::create(["name" => "One Step Closer", "duration" => "231680", "album_id" => "68"]);
Track::create(["name" => "Original Of The Species", "duration" => "281443", "album_id" => "68"]);
Track::create(["name" => "Yahweh", "duration" => "262034", "album_id" => "68"]);
Track::create(["name" => "Discotheque", "duration" => "319582", "album_id" => "69"]);
Track::create(["name" => "Do You Feel Loved", "duration" => "307539", "album_id" => "69"]);
Track::create(["name" => "Mofo", "duration" => "349178", "album_id" => "69"]);
Track::create(["name" => "If God Will Send His Angels", "duration" => "322533", "album_id" => "69"]);
Track::create(["name" => "Staring At The Sun", "duration" => "276924", "album_id" => "69"]);
Track::create(["name" => "Last Night On Earth", "duration" => "285753", "album_id" => "69"]);
Track::create(["name" => "Gone", "duration" => "266866", "album_id" => "69"]);
Track::create(["name" => "Miami", "duration" => "293041", "album_id" => "69"]);
Track::create(["name" => "The Playboy Mansion", "duration" => "280555", "album_id" => "69"]);
Track::create(["name" => "If You Wear That Velvet Dress", "duration" => "315167", "album_id" => "69"]);
Track::create(["name" => "Please", "duration" => "302602", "album_id" => "69"]);
Track::create(["name" => "Wake Up Dead Man", "duration" => "292832", "album_id" => "69"]);
Track::create(["name" => "Helter Skelter", "duration" => "187350", "album_id" => "70"]);
Track::create(["name" => "Van Diemen's Land", "duration" => "186044", "album_id" => "70"]);
Track::create(["name" => "Desire", "duration" => "179226", "album_id" => "70"]);
Track::create(["name" => "Hawkmoon 269", "duration" => "382458", "album_id" => "70"]);
Track::create(["name" => "All Along The Watchtower", "duration" => "264568", "album_id" => "70"]);
Track::create(["name" => "I Still Haven't Found What I'm Looking for", "duration" => "353567", "album_id" => "70"]);
Track::create(["name" => "Freedom For My People", "duration" => "38164", "album_id" => "70"]);
Track::create(["name" => "Silver And Gold", "duration" => "349831", "album_id" => "70"]);
Track::create(["name" => "Pride (In The Name Of Love)", "duration" => "267807", "album_id" => "70"]);
Track::create(["name" => "Angel Of Harlem", "duration" => "229276", "album_id" => "70"]);
Track::create(["name" => "Love Rescue Me", "duration" => "384522", "album_id" => "70"]);
Track::create(["name" => "When Love Comes To Town", "duration" => "255869", "album_id" => "70"]);
Track::create(["name" => "Heartland", "duration" => "303360", "album_id" => "70"]);
Track::create(["name" => "God Part II", "duration" => "195604", "album_id" => "70"]);
Track::create(["name" => "The Star Spangled Banner", "duration" => "43232", "album_id" => "70"]);
Track::create(["name" => "Bullet The Blue Sky", "duration" => "337005", "album_id" => "70"]);
Track::create(["name" => "All I Want Is You", "duration" => "390243", "album_id" => "70"]);
Track::create(["name" => "Pride (In The Name Of Love)", "duration" => "230243", "album_id" => "71"]);
Track::create(["name" => "New Year's Day", "duration" => "258925", "album_id" => "71"]);
Track::create(["name" => "With Or Without You", "duration" => "299023", "album_id" => "71"]);
Track::create(["name" => "I Still Haven't Found What I'm Looking For", "duration" => "280764", "album_id" => "71"]);
Track::create(["name" => "Sunday Bloody Sunday", "duration" => "282174", "album_id" => "71"]);
Track::create(["name" => "Bad", "duration" => "351817", "album_id" => "71"]);
Track::create(["name" => "Where The Streets Have No Name", "duration" => "276218", "album_id" => "71"]);
Track::create(["name" => "I Will Follow", "duration" => "218253", "album_id" => "71"]);
Track::create(["name" => "The Unforgettable Fire", "duration" => "295183", "album_id" => "71"]);
Track::create(["name" => "Sweetest Thing", "duration" => "183066", "album_id" => "71"]);
Track::create(["name" => "Desire", "duration" => "179853", "album_id" => "71"]);
Track::create(["name" => "When Love Comes To Town", "duration" => "258194", "album_id" => "71"]);
Track::create(["name" => "Angel Of Harlem", "duration" => "230217", "album_id" => "71"]);
Track::create(["name" => "All I Want Is You", "duration" => "591986", "album_id" => "71"]);
Track::create(["name" => "Sunday Bloody Sunday", "duration" => "278204", "album_id" => "72"]);
Track::create(["name" => "Seconds", "duration" => "191582", "album_id" => "72"]);
Track::create(["name" => "New Year's Day", "duration" => "336274", "album_id" => "72"]);
Track::create(["name" => "Like A Song...", "duration" => "287294", "album_id" => "72"]);
Track::create(["name" => "Drowning Man", "duration" => "254458", "album_id" => "72"]);
Track::create(["name" => "The Refugee", "duration" => "221283", "album_id" => "72"]);
Track::create(["name" => "Two Hearts Beat As One", "duration" => "243487", "album_id" => "72"]);
Track::create(["name" => "Red Light", "duration" => "225854", "album_id" => "72"]);
Track::create(["name" => "Surrender", "duration" => "333505", "album_id" => "72"]);
Track::create(["name" => "40", "duration" => "157962", "album_id" => "72"]);
Track::create(["name" => "Zooropa", "duration" => "392359", "album_id" => "73"]);
Track::create(["name" => "Babyface", "duration" => "241998", "album_id" => "73"]);
Track::create(["name" => "Numb", "duration" => "260284", "album_id" => "73"]);
Track::create(["name" => "Lemon", "duration" => "418324", "album_id" => "73"]);
Track::create(["name" => "Stay (Faraway, So Close!)", "duration" => "298475", "album_id" => "73"]);
Track::create(["name" => "Daddy's Gonna Pay For Your Crashed Car", "duration" => "320287", "album_id" => "73"]);
Track::create(["name" => "Some Days Are Better Than Others", "duration" => "257436", "album_id" => "73"]);
Track::create(["name" => "The First Time", "duration" => "225697", "album_id" => "73"]);
Track::create(["name" => "Dirty Day", "duration" => "324440", "album_id" => "73"]);
Track::create(["name" => "The Wanderer", "duration" => "283951", "album_id" => "73"]);
Track::create(["name" => "Breakfast In Bed", "duration" => "196179", "album_id" => "75"]);
Track::create(["name" => "Where Did I Go Wrong", "duration" => "226742", "album_id" => "75"]);
Track::create(["name" => "I Would Do For You", "duration" => "334524", "album_id" => "75"]);
Track::create(["name" => "Homely Girl", "duration" => "203833", "album_id" => "75"]);
Track::create(["name" => "Here I Am (Come And Take Me)", "duration" => "242102", "album_id" => "75"]);
Track::create(["name" => "Kingston Town", "duration" => "226951", "album_id" => "75"]);
Track::create(["name" => "Wear You To The Ball", "duration" => "213342", "album_id" => "75"]);
Track::create(["name" => "(I Can't Help) Falling In Love With You", "duration" => "207568", "album_id" => "75"]);
Track::create(["name" => "Higher Ground", "duration" => "260179", "album_id" => "75"]);
Track::create(["name" => "Bring Me Your Cup", "duration" => "341498", "album_id" => "75"]);
Track::create(["name" => "C'est La Vie", "duration" => "270053", "album_id" => "75"]);
Track::create(["name" => "Reggae Music", "duration" => "245106", "album_id" => "75"]);
Track::create(["name" => "Superstition", "duration" => "319582", "album_id" => "75"]);
Track::create(["name" => "Until My Dying Day", "duration" => "235807", "album_id" => "75"]);
Track::create(["name" => "Where Have All The Good Times Gone?", "duration" => "186723", "album_id" => "76"]);
Track::create(["name" => "Hang 'Em High", "duration" => "210259", "album_id" => "76"]);
Track::create(["name" => "Cathedral", "duration" => "82860", "album_id" => "76"]);
Track::create(["name" => "Secrets", "duration" => "206968", "album_id" => "76"]);
Track::create(["name" => "Intruder", "duration" => "100153", "album_id" => "76"]);
Track::create(["name" => "(Oh) Pretty Woman", "duration" => "174680", "album_id" => "76"]);
Track::create(["name" => "Dancing In The Street", "duration" => "225985", "album_id" => "76"]);
Track::create(["name" => "Little Guitars (Intro)", "duration" => "42240", "album_id" => "76"]);
Track::create(["name" => "Little Guitars", "duration" => "228806", "album_id" => "76"]);
Track::create(["name" => "Big Bad Bill (Is Sweet William Now)", "duration" => "165146", "album_id" => "76"]);
Track::create(["name" => "The Full Bug", "duration" => "201116", "album_id" => "76"]);
Track::create(["name" => "Happy Trails", "duration" => "65488", "album_id" => "76"]);
Track::create(["name" => "Eruption", "duration" => "102164", "album_id" => "77"]);
Track::create(["name" => "Ain't Talkin' 'bout Love", "duration" => "228336", "album_id" => "77"]);
Track::create(["name" => "Runnin' With The Devil", "duration" => "215902", "album_id" => "77"]);
Track::create(["name" => "Dance the Night Away", "duration" => "185965", "album_id" => "77"]);
Track::create(["name" => "And the Cradle Will Rock...", "duration" => "213968", "album_id" => "77"]);
Track::create(["name" => "Unchained", "duration" => "208953", "album_id" => "77"]);
Track::create(["name" => "Jump", "duration" => "241711", "album_id" => "77"]);
Track::create(["name" => "Panama", "duration" => "211853", "album_id" => "77"]);
Track::create(["name" => "Why Can't This Be Love", "duration" => "227761", "album_id" => "77"]);
Track::create(["name" => "Dreams", "duration" => "291813", "album_id" => "77"]);
Track::create(["name" => "When It's Love", "duration" => "338991", "album_id" => "77"]);
Track::create(["name" => "Poundcake", "duration" => "321854", "album_id" => "77"]);
Track::create(["name" => "Right Now", "duration" => "321828", "album_id" => "77"]);
Track::create(["name" => "Can't Stop Loving You", "duration" => "248502", "album_id" => "77"]);
Track::create(["name" => "Humans Being", "duration" => "308950", "album_id" => "77"]);
Track::create(["name" => "Can't Get This Stuff No More", "duration" => "315376", "album_id" => "77"]);
Track::create(["name" => "Me Wise Magic", "duration" => "366053", "album_id" => "77"]);
Track::create(["name" => "Runnin' With The Devil", "duration" => "216032", "album_id" => "78"]);
Track::create(["name" => "Eruption", "duration" => "102556", "album_id" => "78"]);
Track::create(["name" => "You Really Got Me", "duration" => "158589", "album_id" => "78"]);
Track::create(["name" => "Ain't Talkin' 'Bout Love", "duration" => "230060", "album_id" => "78"]);
Track::create(["name" => "I'm The One", "duration" => "226507", "album_id" => "78"]);
Track::create(["name" => "Jamie's Cryin'", "duration" => "210546", "album_id" => "78"]);
Track::create(["name" => "Atomic Punk", "duration" => "182073", "album_id" => "78"]);
Track::create(["name" => "Feel Your Love Tonight", "duration" => "222850", "album_id" => "78"]);
Track::create(["name" => "Little Dreamer", "duration" => "203258", "album_id" => "78"]);
Track::create(["name" => "Ice Cream Man", "duration" => "200306", "album_id" => "78"]);
Track::create(["name" => "On Fire", "duration" => "180636", "album_id" => "78"]);
Track::create(["name" => "Neworld", "duration" => "105639", "album_id" => "79"]);
Track::create(["name" => "Without You", "duration" => "390295", "album_id" => "79"]);
Track::create(["name" => "One I Want", "duration" => "330788", "album_id" => "79"]);
Track::create(["name" => "From Afar", "duration" => "324414", "album_id" => "79"]);
Track::create(["name" => "Dirty Water Dog", "duration" => "327392", "album_id" => "79"]);
Track::create(["name" => "Once", "duration" => "462837", "album_id" => "79"]);
Track::create(["name" => "Fire in the Hole", "duration" => "331728", "album_id" => "79"]);
Track::create(["name" => "Josephina", "duration" => "342491", "album_id" => "79"]);
Track::create(["name" => "Year to the Day", "duration" => "514612", "album_id" => "79"]);
Track::create(["name" => "Primary", "duration" => "86987", "album_id" => "79"]);
Track::create(["name" => "Ballot or the Bullet", "duration" => "342282", "album_id" => "79"]);
Track::create(["name" => "How Many Say I", "duration" => "363937", "album_id" => "79"]);
Track::create(["name" => "Instant Karma", "duration" => "193188", "album_id" => "74"]);
Track::create(["name" => "#9 Dream", "duration" => "278312", "album_id" => "74"]);
Track::create(["name" => "Mother", "duration" => "287740", "album_id" => "74"]);
Track::create(["name" => "Give Peace a Chance", "duration" => "274644", "album_id" => "74"]);
Track::create(["name" => "Cold Turkey", "duration" => "281424", "album_id" => "74"]);
Track::create(["name" => "Whatever Gets You Thru the Night", "duration" => "215084", "album_id" => "74"]);
Track::create(["name" => "I'm Losing You", "duration" => "240719", "album_id" => "74"]);
Track::create(["name" => "Gimme Some Truth", "duration" => "232778", "album_id" => "74"]);
Track::create(["name" => "Oh, My Love", "duration" => "159473", "album_id" => "74"]);
Track::create(["name" => "Imagine", "duration" => "192329", "album_id" => "74"]);
Track::create(["name" => "Nobody Told Me", "duration" => "210348", "album_id" => "74"]);
Track::create(["name" => "Jealous Guy", "duration" => "239094", "album_id" => "74"]);
Track::create(["name" => "Working Class Hero", "duration" => "265449", "album_id" => "74"]);
Track::create(["name" => "Power to the People", "duration" => "213018", "album_id" => "74"]);
Track::create(["name" => "Imagine", "duration" => "219078", "album_id" => "74"]);
Track::create(["name" => "Beautiful Boy", "duration" => "227995", "album_id" => "74"]);
Track::create(["name" => "Isolation", "duration" => "156059", "album_id" => "74"]);
Track::create(["name" => "Watching the Wheels", "duration" => "198645", "album_id" => "74"]);
Track::create(["name" => "Grow Old With Me", "duration" => "149093", "album_id" => "74"]);
Track::create(["name" => "Gimme Some Truth", "duration" => "187546", "album_id" => "74"]);
Track::create(["name" => "[Just Like] Starting Over", "duration" => "215549", "album_id" => "74"]);
Track::create(["name" => "God", "duration" => "260410", "album_id" => "74"]);
Track::create(["name" => "Real Love", "duration" => "236911", "album_id" => "74"]);
Track::create(["name" => "Rock You Like a Hurricane", "duration" => "255766", "album_id" => "80"]);
Track::create(["name" => "No One Like You", "duration" => "240325", "album_id" => "80"]);
Track::create(["name" => "The Zoo", "duration" => "332740", "album_id" => "80"]);
Track::create(["name" => "Loving You Sunday Morning", "duration" => "339125", "album_id" => "80"]);
Track::create(["name" => "Still Loving You", "duration" => "390674", "album_id" => "80"]);
Track::create(["name" => "Big City Nights", "duration" => "251865", "album_id" => "80"]);
Track::create(["name" => "Believe in Love", "duration" => "325774", "album_id" => "80"]);
Track::create(["name" => "Rhythm of Love", "duration" => "231246", "album_id" => "80"]);
Track::create(["name" => "I Can't Explain", "duration" => "205332", "album_id" => "80"]);
Track::create(["name" => "Tease Me Please Me", "duration" => "287229", "album_id" => "80"]);
Track::create(["name" => "Wind of Change", "duration" => "315325", "album_id" => "80"]);
Track::create(["name" => "Send Me an Angel", "duration" => "273041", "album_id" => "80"]);
Track::create(["name" => "War Pigs", "duration" => "234013", "album_id" => "81"]);
Track::create(["name" => "Revelations", "duration" => "252376", "album_id" => "3"]);
Track::create(["name" => "One and the Same", "duration" => "217732", "album_id" => "3"]);
Track::create(["name" => "Sound of a Gun", "duration" => "260154", "album_id" => "3"]);
Track::create(["name" => "Until We Fall", "duration" => "230758", "album_id" => "3"]);
Track::create(["name" => "Original Fire", "duration" => "218916", "album_id" => "3"]);
Track::create(["name" => "Broken City", "duration" => "228366", "album_id" => "3"]);
Track::create(["name" => "Somedays", "duration" => "213831", "album_id" => "3"]);
Track::create(["name" => "Shape of Things to Come", "duration" => "274597", "album_id" => "3"]);
Track::create(["name" => "Jewel of the Summertime", "duration" => "233242", "album_id" => "3"]);
Track::create(["name" => "Wide Awake", "duration" => "266308", "album_id" => "3"]);
Track::create(["name" => "Nothing Left to Say But Goodbye", "duration" => "213041", "album_id" => "3"]);
Track::create(["name" => "Moth", "duration" => "298049", "album_id" => "3"]);
Track::create(["name" => "Show Me How to Live (Live at the Quart Festival)", "duration" => "301974", "album_id" => "3"]);
Track::create(["name" => 'Band Members Discuss Tracks from "Revelations"', "duration" => "294294", "album_id" => "3"]);
    }
}
